name: Build and Push Google Photo API

on:
  push:
    branches:
      - main
    paths:
      - "google-photo-api/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image using docker
        run: |
          docker build \
            -t wonchoe/google-photo-api:latest \
            -f google-photo-api/Dockerfile \
            google-photo-api

          docker tag wonchoe/google-photo-api:latest wonchoe/google-photo-api:${{ github.run_number }}

      - name: Push image
        run: |
          docker push wonchoe/google-photo-api:latest
          docker push wonchoe/google-photo-api:${{ github.run_number }}
