name: Build and Push Google Photo API

on:
  push:
    branches:
      - main
    paths:
      - "google-photo-api/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull cache image (if exists)
        run: |
          docker pull wonchoe/google-photo-api:buildcache || true

      - name: Build image using docker with REGISTRY CACHE
        run: |
          docker build \
            --cache-from wonchoe/google-photo-api:buildcache \
            -t wonchoe/google-photo-api:latest \
            -t wonchoe/google-photo-api:${{ github.sha }} \
            -f google-photo-api/Dockerfile \
            google-photo-api

      - name: Push image
        run: |
          docker push wonchoe/google-photo-api:latest
          docker push wonchoe/google-photo-api:${{ github.sha }}

      - name: Push cache layer
        run: |
          docker tag wonchoe/google-photo-api:latest wonchoe/google-photo-api:buildcache
          docker push wonchoe/google-photo-api:buildcache
